[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"  # Updated to a more recent version
  NPM_VERSION = "9"    # Updated to a more recent version

# This redirects all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
